mb/erying/tgl: Change REFCLK to 100MHz
With XMP enabled, system failed stability tests if REFCLK was set to
133MHz.

`../../gcc-11.4.0/gcc/tree-ssa-loop-split.c:1696:1: internal compiler
error: Segmentation fault`

Changing to 100MHz. Seems to be stable (so far).

Signed-off-by: Alicja Michalska <ahplka19@gmail.com>